{{- $vaultAnnotations := include "devops-info-service.vaultAnnotations" . | trim }}
{{- $configFileChecksum := include "devops-info-service.configFileContent" . | sha256sum }}
{{- $configEnvChecksum := include "devops-info-service.envConfigData" . | sha256sum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-info-service.fullname" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "devops-info-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-file: {{ $configFileChecksum | quote }}
        checksum/config-env: {{ $configEnvChecksum | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $vaultAnnotations }}
        {{- $vaultAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "devops-info-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-info-service.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      containers:
        - name: {{ include "devops-info-service.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- include "devops-info-service.envVars" . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "devops-info-service.envConfigMapName" . }}
          {{- if and .Values.secret.enabled .Values.secret.envFrom }}
            - secretRef:
                name: {{ include "devops-info-service.secretName" . }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "devops-info-service.fileConfigMapName" . }}
        {{- if .Values.persistence.enabled }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "devops-info-service.pvcName" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
